# Generated by Django 5.0.3 on 2024-04-01 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VentaCamiseta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_camiseta', models.CharField(max_length=50, unique=True)),
                ('marca', models.CharField(max_length=120)),
                ('talla_camiseta', models.CharField(max_length=20)),
                ('cantidad_camiseta', models.IntegerField()),
                ('precio_camiseta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nombre_cliente', models.CharField(max_length=100)),
                ('metodo_de_pago', models.CharField(max_length=50)),
                ('fecha_de_pago', models.DateField()),
                ('pais', models.CharField(max_length=120)),
                ('ciudad', models.CharField(max_length=120)),
                ('barrio', models.CharField(max_length=120)),
            ],
        ),
    ]
